import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
test('admin adds, assigns, renames and hides product categories on mobile',async({page})=>{
 execFileSync(process.execPath,['--input-type=module','-e',"import {configureAdmin} from './server/catalogue.mjs';configureAdmin('category-admin','category-test-password-123');"],{env:{...process.env,DATA_DIR:process.env.DATA_DIR||'.test-data'},cwd:process.cwd()});
 await page.setViewportSize({width:360,height:800});await page.goto('/admin');await page.getByLabel('Username',{exact:true}).fill('category-admin');await page.getByLabel('Password',{exact:true}).fill('category-test-password-123');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByText('Signed in as')).toBeVisible();
 await page.getByLabel('Category name',{exact:true}).fill('Browser Accessories');await page.getByRole('button',{name:'Add category',exact:true}).click();await expect(page.getByText('Category saved.',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'+ Add product',exact:true}).click();await page.getByLabel('Product title *',{exact:true}).fill('Browser category item');await page.getByLabel('Category *',{exact:true}).selectOption('Browser Accessories');await page.getByLabel('Product image URL or /path *',{exact:true}).fill('/blog-images/blog-1.jpg');await page.getByLabel('Product link *',{exact:true}).fill('https://example.com/product');await page.getByLabel('Published — visible to visitors').check();await page.getByRole('button',{name:'Save item',exact:true}).click();await expect(page.getByText(/Item saved/)).toBeVisible();
 await page.goto('/');await expect(page.getByRole('group',{name:'Browse product categories'})).toContainText('Browser Accessories');await page.getByRole('button',{name:'Browser Accessories',exact:true}).click();await expect(page.locator('#featured-products article')).toHaveCount(1);
 await page.goto('/admin');await page.getByRole('button',{name:'Edit category Browser Accessories',exact:true}).click();await page.getByLabel('Category name',{exact:true}).fill('Renamed Accessories');await page.getByRole('button',{name:'Save category',exact:true}).click();await expect(page.getByText('Category saved.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Edit category Renamed Accessories',exact:true}).click();await page.getByLabel('Show in visitor filters').uncheck();await page.getByRole('button',{name:'Save category',exact:true}).click();await expect(page.getByText('Category saved.',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:'previews/category-manager-mobile.png',fullPage:true});
 await page.goto('/');await expect(page.getByRole('group',{name:'Browse product categories'})).not.toContainText('Renamed Accessories');await page.getByLabel('Search shop products').fill('Browser category item');await page.getByRole('button',{name:'Submit product search'}).click();await expect(page.locator('#featured-products article')).toHaveCount(1);await expect(page.locator('#featured-products article')).toContainText('Renamed Accessories');
 await page.goto('/admin');await page.getByLabel('Search catalogue').fill('Browser category item');page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Delete Browser category item',exact:true}).click();await expect(page.getByText('Item deleted.',{exact:true})).toBeVisible();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Delete category Renamed Accessories',exact:true}).click();await expect(page.getByText('Category deleted.',{exact:true})).toBeVisible();
});

// Keep non-analytics checks independent of the optional analytics banner.
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('khan-analytics-choice','declined'));});
