import { test,expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
const routes=['/','/tools','/library','/background-remover','/compiler','/pdf-toolkit','/image-tools','/music-library'];
test('store resources open separate pages, products align and library files load',async({page,request})=>{
 await page.goto('/');await expect(page.locator('#services')).toHaveCount(0);await expect(page.locator('#books')).toHaveCount(0);await expect(page.getByRole('heading',{name:'Discover your next everyday favourite.'})).toBeVisible();
 const link=page.locator('#resources a[href="/tools"]');await expect(link).toHaveAttribute('target','_blank');const popupPromise=page.waitForEvent('popup');await link.click();const popup=await popupPromise;await expect(popup.locator('h1')).toBeVisible();await popup.close();
 await page.locator('#featured-products').scrollIntoViewIfNeeded();await page.waitForFunction(()=>Array.from(document.querySelectorAll('#featured-products img')).every(i=>(i as HTMLImageElement).complete));const rects=await page.locator('#featured-products article').evaluateAll(els=>els.map(e=>({card:e.getBoundingClientRect().height,image:e.querySelector('img')!.getBoundingClientRect().height,button:e.querySelector('a')!.getBoundingClientRect().bottom})));expect(Math.abs(rects[0].card-rects[1].card)).toBeLessThan(1);expect(Math.abs(rects[0].image-rects[1].image)).toBeLessThan(1);expect(Math.abs(rects[0].button-rects[1].button)).toBeLessThan(1);
 await page.getByLabel('Search products').fill('no-match-test');await expect(page.getByText('No products match your search.')).toBeVisible();await page.getByRole('button',{name:'Show all products',exact:true}).click();
 await page.goto('/library');await expect(page.locator('#books article')).toHaveCount(10);const urls=await page.locator('#books a[download]').evaluateAll(els=>els.map(e=>(e as HTMLAnchorElement).href));for(const url of urls){const response=await request.get(url);expect(response.ok()).toBeTruthy();expect(response.headers()['content-type']).toContain('application/pdf');}
});
test('all routes fit narrow mobile and have working metadata/navigation',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:900});for(const route of routes){await page.goto(route);await expect(page.locator('h1')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await expect(page).toHaveTitle(/Khan Productions/);}}
 await page.setViewportSize({width:390,height:844});await page.goto('/');await page.getByRole('button',{name:'Open navigation'}).click();await page.locator('#mobile-nav').getByRole('link',{name:'Library',exact:true}).click();await expect(page).toHaveURL(/\/library$/);expect(errors).toEqual([]);
});
test('automated accessibility and screenshots in light and dark',async({page})=>{
 for(const theme of ['light','dark']){await page.goto('/');await page.evaluate(t=>localStorage.setItem('khan-theme',t),theme);for(const route of routes){await page.goto(route);await expect(page.locator('h1')).toBeVisible();const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(result.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))).toEqual([]);}await page.goto('/');await page.screenshot({path:`previews/store-${theme}.png`});}
 await page.setViewportSize({width:390,height:844});await page.goto('/');await page.getByRole('button',{name:'Switch to light mode'}).click();await page.screenshot({path:'previews/store-mobile.png'});await page.goto('/tools');await page.screenshot({path:'previews/tools-dashboard.png',fullPage:true});
});
