import { test,expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { execFileSync } from 'node:child_process';
const routes=['/','/tools','/library','/background-remover','/pdf-toolkit','/image-tools','/music-library','/admin','/privacy','/affiliate-disclosure'];
test('catalogue filters, pagination, density, covers and resources',async({page})=>{
 await page.goto('/');await expect(page.getByRole('heading',{name:'Discover your next everyday favourite.'})).toBeVisible();await expect(page.locator('a[href="/compiler"]')).toHaveCount(0);
 await page.locator('#featured-products').scrollIntoViewIfNeeded();await expect(page.locator('#featured-products article')).toHaveCount(12);await page.getByLabel('Search shop products').fill('no-match-test');await page.getByRole('button',{name:'Submit product search'}).click();await expect(page.getByText('No products match your search.')).toBeVisible();await page.getByRole('button',{name:'Show all products',exact:true}).click();
 await page.getByLabel('Per page').selectOption('6');await expect(page.locator('#featured-products article')).toHaveCount(6);const first=await page.locator('#featured-products article h3').first().innerText();await page.getByRole('button',{name:'Next →',exact:true}).click();expect(await page.locator('#featured-products article h3').first().innerText()).not.toBe(first);await expect(page.getByRole('button',{name:'Compact view'})).toHaveCount(0);await page.getByLabel('Sort',{exact:true}).selectOption('az');await expect(page.getByText(/Page 1 of/)).toBeVisible();
 await page.goto('/library');await expect(page.locator('#books article')).toHaveCount(10);await expect(page.locator('#books article a').first()).toHaveAttribute('href',/^https:\/\/drive.google.com/);await page.getByLabel('Search books').fill('sherlock');await expect(page.locator('#books article')).toHaveCount(1);
 await page.goto('/music-library');await expect(page.locator('audio')).toHaveCount(6);const covers=await page.locator('article img').evaluateAll(imgs=>imgs.map(i=>(i as HTMLImageElement).src));expect(new Set(covers).size).toBe(6);
});
test('all routes fit phone, tablet, desktop and landscape in both themes',async({page})=>{
 test.setTimeout(180000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 for(const theme of ['light','dark']){await page.goto('/');await page.evaluate(t=>localStorage.setItem('khan-theme',t),theme);for(const viewport of [{width:320,height:800},{width:360,height:800},{width:390,height:844},{width:430,height:932},{width:768,height:1024},{width:844,height:390},{width:1280,height:900}]){await page.setViewportSize(viewport);for(const route of routes){await page.goto(route);await expect(page.locator('h1')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${route} ${theme} ${viewport.width}`).toBeTruthy();await expect(page).toHaveTitle(/Khan Productions/);}}}
 await page.setViewportSize({width:390,height:844});await page.goto('/');await page.getByRole('button',{name:'Open navigation'}).click();await page.locator('#mobile-nav').getByRole('link',{name:'Library',exact:true}).click();await expect(page).toHaveURL(/\/library$/);expect(errors).toEqual([]);
});
test('accessibility, images and visual previews in both themes',async({page})=>{
 test.setTimeout(180000);
 for(const theme of ['light','dark']){await page.goto('/');await page.evaluate(t=>localStorage.setItem('khan-theme',t),theme);for(const route of ['/','/library','/music-library','/admin','/tools']){await page.goto(route);await expect(page.locator('h1')).toBeVisible();await page.evaluate(()=>{document.querySelectorAll<HTMLImageElement>('img').forEach(i=>i.loading='eager');});await page.waitForFunction(()=>Array.from(document.images).every(i=>i.complete));expect(await page.evaluate(()=>Array.from(document.images).filter(i=>!i.naturalWidth).map(i=>i.src))).toEqual([]);const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(result.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))).toEqual([]);}
 await page.goto('/');await page.screenshot({path:`previews/store-${theme}.png`});await page.locator('#featured-products').scrollIntoViewIfNeeded();await page.evaluate(()=>document.querySelectorAll('img').forEach(i=>i.loading='eager'));await page.waitForFunction(()=>Array.from(document.images).every(i=>i.complete));await page.screenshot({path:`previews/products-${theme}.png`});await page.goto('/music-library');await page.screenshot({path:`previews/music-${theme}.png`,fullPage:true});}
 await page.setViewportSize({width:390,height:844});await page.goto('/');await page.evaluate(()=>localStorage.setItem('khan-theme','light'));await page.reload();await page.screenshot({path:'previews/store-mobile.png'});await page.goto('/library');await page.screenshot({path:'previews/library-mobile.png'});
});
test('admin creates a draft, publishes for visitors, edits and deletes',async({page,request})=>{
 execFileSync(process.execPath,['--input-type=module','-e',"import {configureAdmin} from './server/catalogue.mjs';configureAdmin('browser-admin','browser-test-password-123');"],{env:{...process.env,DATA_DIR:process.env.DATA_DIR||'.test-data'},cwd:process.cwd()});
 await page.goto('/admin');await page.getByLabel('Username',{exact:true}).fill('browser-admin');await page.getByLabel('Password',{exact:true}).fill('browser-test-password-123');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByText('Signed in as')).toBeVisible();
 await page.getByRole('button',{name:'Books',exact:true}).click();await page.getByLabel('Category name',{exact:true}).fill('Testing');await page.getByRole('button',{name:'Add category',exact:true}).click();await expect(page.getByText('Category saved.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'+ Add book',exact:true}).click();await page.getByLabel('Book title *',{exact:true}).fill('Admin browser test');await page.getByLabel('Author *',{exact:true}).fill('Test author');await page.getByLabel('Genre *',{exact:true}).selectOption('Testing');await page.getByLabel('PDF / Google Drive link *',{exact:true}).fill('https://example.com/book.pdf');await page.getByRole('button',{name:'Save item',exact:true}).click();await expect(page.getByRole('status').last()).toContainText('Item saved');
 expect((await (await request.get('/api/catalogue')).json()).books.some((b:{title:string})=>b.title==='Admin browser test')).toBe(false);
 await page.getByRole('button',{name:'Edit Admin browser test',exact:true}).click();await page.getByLabel('Published — visible to visitors').check();await page.getByRole('button',{name:'Save item',exact:true}).click();await expect(page.getByRole('status').last()).toContainText('Item saved');
 await page.goto('/library');await page.getByLabel('Search books').fill('Admin browser test');await expect(page.locator('#books article')).toHaveCount(1);await page.goto('/admin');await page.getByRole('button',{name:'Books',exact:true}).click();page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Delete Admin browser test',exact:true}).click();await expect(page.getByRole('status').last()).toContainText('Item deleted');await page.getByRole('button',{name:'Sign out'}).click();await expect(page.getByRole('heading',{name:'Admin sign in'})).toBeVisible();
});

test('admin product image upload and music cover fallback survive edits',async({page,request})=>{
 execFileSync(process.execPath,['--input-type=module','-e',"import {configureAdmin} from './server/catalogue.mjs';configureAdmin('browser-admin','browser-test-password-123');"],{env:{...process.env,DATA_DIR:process.env.DATA_DIR||'.test-data'},cwd:process.cwd()});
 await page.goto('/admin');await page.getByLabel('Username',{exact:true}).fill('browser-admin');await page.getByLabel('Password',{exact:true}).fill('browser-test-password-123');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByText('Signed in as')).toBeVisible();
 await page.getByLabel('Category name',{exact:true}).fill('Testing');await page.getByRole('button',{name:'Add category',exact:true}).click();await expect(page.getByText('Category saved.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'+ Add product',exact:true}).click();await page.getByLabel('Product title *',{exact:true}).fill('Browser uploaded product');await page.getByLabel('Category *',{exact:true}).selectOption('Testing');await page.getByLabel('Product link *',{exact:true}).fill('https://example.com/product');
 await page.locator('#admin-cover').setInputFiles('public/blog-images/blog-1.jpg');await expect(page.getByRole('status').last()).toContainText('Image uploaded');await expect.poll(()=>page.getByAltText('Cover preview').evaluate(i=>(i as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);await expect(page.getByLabel('Product image URL or /path *',{exact:true})).toHaveValue(/^\/uploads\//);await page.getByLabel('Published — visible to visitors').check();await page.getByRole('button',{name:'Save item',exact:true}).click();await expect(page.getByRole('status').last()).toContainText('Item saved');await page.goto('/');await page.getByLabel('Search shop products').fill('Browser uploaded product');await page.getByRole('button',{name:'Submit product search'}).click();const product=page.locator('#featured-products article');await expect(product).toHaveCount(1);await product.scrollIntoViewIfNeeded();await expect(product.locator('img')).toHaveJSProperty('complete',true);expect(await product.locator('img').evaluate(i=>(i as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
 await page.goto('/admin');await page.getByLabel('Search catalogue').fill('Browser uploaded product');page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Delete Browser uploaded product',exact:true}).click();await expect(page.getByRole('status').last()).toContainText('Item deleted');
 await page.getByRole('button',{name:'Music',exact:true}).click();await page.getByLabel('Category name',{exact:true}).fill('Testing');await page.getByRole('button',{name:'Add category',exact:true}).click();await expect(page.getByText('Category saved.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'+ Add track',exact:true}).click();await page.getByLabel('Track title *',{exact:true}).fill('Browser cover fallback');await page.getByLabel('Artist *',{exact:true}).fill('Test artist');await page.getByLabel('Genre *',{exact:true}).selectOption('Testing');const catalogue=await (await request.get('/api/catalogue')).json();await page.getByLabel('Audio URL or /music/path.mp3 *',{exact:true}).fill(catalogue.music[0].url);await page.getByLabel('Usage rights / licence *',{exact:true}).fill('Test only');await page.getByLabel('Published — visible to visitors').check();await page.getByRole('button',{name:'Save item',exact:true}).click();await expect(page.getByRole('status').last()).toContainText('Item saved');
 await page.goto('/music-library');await page.getByLabel('Search by track or artist').fill('Browser cover fallback');const cover=page.locator('article img');await expect(cover).toHaveAttribute('src',/^data:image\/svg\+xml/);expect(decodeURIComponent(await cover.getAttribute('src')||'')).not.toContain('<text');
 await page.goto('/admin');await page.getByRole('button',{name:'Music',exact:true}).click();await page.getByLabel('Search catalogue').fill('Browser cover fallback');await page.getByRole('button',{name:'Edit Browser cover fallback',exact:true}).click();await page.getByLabel('Track cover URL or /path',{exact:true}).fill('/missing-cover-test.png');await page.getByRole('button',{name:'Save item',exact:true}).click();await expect(page.getByRole('status').last()).toContainText('Item saved');await page.goto('/music-library');await page.getByLabel('Search by track or artist').fill('Browser cover fallback');await page.locator('article').scrollIntoViewIfNeeded();await expect(page.locator('article img')).toHaveAttribute('src',/^data:image\/svg\+xml/);
 await page.goto('/admin');await page.getByRole('button',{name:'Music',exact:true}).click();await page.getByLabel('Search catalogue').fill('Browser cover fallback');page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Delete Browser cover fallback',exact:true}).click();await expect(page.getByRole('status').last()).toContainText('Item deleted');await page.getByRole('button',{name:'Sign out'}).click();
});
