import { test,expect } from '@playwright/test';
import { PDFDocument } from 'pdf-lib';
import { readFile } from 'node:fs/promises';

test('PDF merge and extract produce valid PDFs with correct page counts',async({page})=>{
 const doc=await PDFDocument.create();doc.addPage();doc.addPage();const data=Buffer.from(await doc.save());await page.goto('/pdf-toolkit');await page.getByLabel('2. Choose').setInputFiles([{name:'one.pdf',mimeType:'application/pdf',buffer:data},{name:'two.pdf',mimeType:'application/pdf',buffer:data}]);await page.getByRole('button',{name:'Process Files'}).click();await expect(page.getByRole('status')).toContainText('4 pages');const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download PDF'}).click()]);const output=await PDFDocument.load(await readFile((await download.path())!));expect(output.getPageCount()).toBe(4);
 await page.getByLabel('1. Choose an action').selectOption('extract');await page.getByLabel('2. Choose').setInputFiles({name:'one.pdf',mimeType:'application/pdf',buffer:data});await page.getByLabel('3. Pages in output order').fill('2');await page.getByRole('button',{name:'Process Files'}).click();await expect(page.getByRole('status')).toContainText('1 pages');await page.getByLabel('3. Pages in output order').fill('9');await page.getByRole('button',{name:'Process Files'}).click();await expect(page.getByRole('alert')).toContainText('between 1 and 2');
});
test('image export creates correct sized JPG and validates upload',async({page})=>{
 await page.goto('/image-tools');const png=await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=100;c.height=50;return c.toDataURL('image/png').split(',')[1];});await page.getByLabel('1. Choose image').setInputFiles({name:'test.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await expect(page.getByLabel('Width (pixels)')).toHaveValue('100');await page.getByLabel('Format',{exact:true}).selectOption('image/jpeg');await page.getByLabel('Width (pixels)').fill('80');await expect(page.getByLabel('Height (pixels)')).toHaveValue('40');await page.getByRole('button',{name:'Convert Image'}).click();await expect(page.getByAltText('Converted image')).toBeVisible();expect(await page.getByAltText('Converted image').evaluate((img:HTMLImageElement)=>img.naturalWidth)).toBe(80);const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download Image'}).click()]);expect(download.suggestedFilename()).toBe('test-converted.jpg');
});
test('music paths load, playback succeeds, search and favourites work',async({page,request})=>{
 await page.goto('/music-library');await expect(page.getByRole('status')).toContainText('6 tracks');const source=await page.locator('audio').getAttribute('src');expect((await request.get(source!)).ok()).toBeTruthy();await page.getByRole('button',{name:'Play selected track'}).click();await expect.poll(()=>page.locator('audio').evaluate((a:HTMLAudioElement)=>!a.paused)).toBeTruthy();await page.getByLabel('Save Escape Your Love',{exact:true}).click();await page.getByLabel('Show saved tracks only').check();await expect(page.getByRole('status')).toContainText('1 tracks');await page.getByLabel('Search by track or artist').fill('no-match');await expect(page.getByText('No tracks match your filters.')).toBeVisible();
});
test('API tools display configuration errors, no fabricated successes',async({page})=>{
 await page.goto('/compiler');await page.getByRole('button',{name:'Run Code'}).click();await expect(page.getByRole('alert')).toContainText('not been configured');await page.getByRole('button',{name:'Open AI assistant'}).click();await page.getByLabel('Your question').fill('How can I merge PDFs?');await page.getByRole('button',{name:'Send',exact:true}).click();await expect(page.locator('#assistant-panel [role=alert]')).toContainText('not been configured');await page.getByRole('button',{name:'Close assistant',exact:true}).click();
 await page.goto('/background-remover');const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=5;c.height=5;return c.toDataURL().split(',')[1];});await page.getByLabel('1. Choose an image').setInputFiles({name:'test.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.getByRole('button',{name:'2. Remove Background'}).click();await expect(page.getByRole('alert')).toContainText('not been configured');
});

test('batch images preserve individual proportions and ZIP contains every export',async({page})=>{
 await page.goto('/image-tools');const pngs=await page.evaluate(()=>[50,100].map(h=>{const c=document.createElement('canvas');c.width=100;c.height=h;return c.toDataURL().split(',')[1];}));await page.getByLabel('1. Choose image').setInputFiles(pngs.map((p,i)=>({name:`image-${i}.png`,mimeType:'image/png',buffer:Buffer.from(p,'base64')})));await page.getByLabel('Width (pixels)').fill('80');await page.getByRole('button',{name:'Convert Image'}).click();await expect(page.getByRole('heading',{name:'Batch results'})).toBeVisible();const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download All as ZIP'}).click()]);const {default:JSZip}=await import('jszip');const zip=await JSZip.loadAsync(await readFile((await download.path())!));expect(Object.keys(zip.files)).toHaveLength(2);
});
