import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { Link } from 'react-router-dom';
const privacy=[
 ['Contact information','When you contact us, you provide your name, email address, subject and message. We use these details to respond to your enquiry. Direct form submissions, when available, pass through our hosting service and Resend email delivery service to our support inbox. If you choose the email link instead, your own mail provider handles sending. Do not include passwords, payment details or sensitive documents.'],
 ['AI assistant','Messages sent to the assistant are processed by our backend and the configured AI provider to generate a reply. The website uses a Google Gemini integration; provider processing is subject to its own terms and privacy practices. Avoid sharing private or sensitive information in chat.'],
 ['Images and PDF tools','Image conversion, compression, PDF editing and background removal run in your browser. These tools do not require sending your selected files to our catalogue server. Background removal may download model files from an external provider. Catalogue image uploads made by an administrator are stored on our hosting service.'],
 ['Browser storage and essential cookies','Your browser may store appearance preferences and saved music favourites. Administrator sign-in uses an essential session cookie. You can clear browser storage through your browser settings, which also clears saved preferences.'],
 ['Hosting and external websites','Our hosting and service providers may process technical information such as IP addresses and request logs to deliver and protect the website. Amazon and linked social or resource websites have their own privacy practices. This notice does not describe data processing on those external websites.'],
 ['Questions and deletion requests','Contact khanproductions7867@gmail.com to ask about information you have shared with us or request its deletion. We keep support correspondence as needed to handle enquiries and related records; providers may apply their own retention periods. This notice will be updated when the website’s data practices change.']
];
const affiliate=[
 ['Product links and commissions','Some links to products may be affiliate links. If you follow an affiliate link and make a qualifying purchase, Khan Productions may receive a commission. Affiliate eligibility and commissions depend on the relevant programme.'],
 ['Where purchases happen','This website helps you browse products and directs you to Amazon. We do not collect payment or place orders here. Confirm the current price, shipping, seller information, returns and availability on Amazon before purchasing.'],
 ['Ratings and product information','Listed ratings and product details come from supplied catalogue information and may change. They are not customer reviews collected on Khan Productions. Badges such as “New”, “Trending” and “Best Seller” are catalogue labels, not verified live sales rankings.'],
 ['Make an informed choice','A listing is not a guarantee that a product will suit your needs. Compare the exact model and manufacturer information, and read recent seller-page reviews. Contact us if you notice an inaccurate listing.']
];
export default function TrustPage({kind}:{kind:'privacy'|'affiliate'}){const isPrivacy=kind==='privacy';return <><Navbar/><main id="main-content" className="section-shell pt-32"><div className="section-inner max-w-3xl"><p className="eyebrow">Khan Productions</p><h1 className="section-heading">{isPrivacy?'Privacy notice':'Affiliate disclosure'}</h1><p className="mt-3 text-sm text-muted-foreground">Updated 8 October 2026</p><div className="mt-8 space-y-8">{(isPrivacy?privacy:affiliate).map(([title,text])=><section key={title}><h2 className="text-xl font-semibold">{title}</h2><p className="mt-3 leading-relaxed text-muted-foreground">{text}</p></section>)}</div><Link to="/#contact" className="action mt-8">Contact support</Link></div></main><Footer/></>}
