import { useEffect,useRef,useState } from 'react';
import { MessageCircle,X } from 'lucide-react';
import { api } from '@/lib/tool-utils';
type Message={role:'user'|'assistant';content:string};
export default function Assistant(){const [open,setOpen]=useState(false);const [messages,setMessages]=useState<Message[]>([]);const [input,setInput]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const field=useRef<HTMLInputElement>(null);const toggle=useRef<HTMLButtonElement>(null);const end=useRef<HTMLDivElement>(null);
useEffect(()=>{if(open)field.current?.focus();},[open]);useEffect(()=>{end.current?.scrollIntoView({block:'nearest'});},[messages,busy]);
function close(){setOpen(false);toggle.current?.focus();}
async function send(text=input){if(!text.trim()||busy)return;const next:Message[]=[...messages,{role:'user',content:text.trim()}];setMessages(next);setInput('');setBusy(true);setError('');try{const r=await api<{answer:string}>('/api/chat',{messages:next.slice(-20)});setMessages([...next,{role:'assistant',content:r.answer}]);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
return <><button ref={toggle} aria-label={open?'Close AI assistant':'Open AI assistant'} aria-expanded={open} aria-controls="assistant-panel" onClick={()=>open?close():setOpen(true)} className="fixed bottom-5 right-5 z-50 flex h-14 items-center gap-2 rounded-full bg-primary px-5 font-semibold text-primary-foreground shadow-lg"><MessageCircle aria-hidden="true" className="h-5 w-5"/><span className="hidden sm:inline">Ask Assistant</span></button>{open&&<section id="assistant-panel" role="dialog" aria-labelledby="assistant-title" onKeyDown={e=>{if(e.key==='Escape')close();}} className="fixed bottom-24 right-3 z-50 flex max-h-[70vh] w-[calc(100%-1.5rem)] max-w-sm flex-col rounded-2xl border border-border bg-card text-card-foreground shadow-xl"><header className="flex items-center justify-between border-b border-border p-4"><h2 id="assistant-title" className="font-semibold">Khan AI Assistant</h2><button onClick={close} aria-label="Close assistant" className="flex h-11 w-11 items-center justify-center"><X aria-hidden="true"/></button></header><div className="overflow-y-auto p-4"><p className="mb-4 text-sm text-muted-foreground">Ask about our tools, products or library. AI answers may need checking. Messages are sent to the configured AI provider.</p>{!messages.length&&<div className="flex flex-wrap gap-2">{['Which tool should I use?','How do I merge PDFs?'].map(s=><button key={s} className="secondary-action text-sm" onClick={()=>send(s)}>{s}</button>)}</div>}<div role="log" aria-live="polite" aria-relevant="additions">{messages.map((m,i)=><div key={i} className={`my-3 rounded-xl p-3 text-sm ${m.role==='user'?'bg-primary text-primary-foreground':'bg-muted'}`}><p className="mb-1 font-semibold">{m.role==='user'?'You':'Assistant'}</p><p className="whitespace-pre-wrap break-words">{m.content}</p></div>)}</div>{busy&&<p role="status" className="text-sm">Assistant is replying…</p>}{error&&<p className="error" role="alert">{error}</p>}<div ref={end}/></div><form className="tool-panel rounded-t-none border-x-0 border-b-0" onSubmit={e=>{e.preventDefault();void send();}}><label htmlFor="assistant-question">Your question</label><input ref={field} id="assistant-question" value={input} maxLength={4000} disabled={busy} onChange={e=>setInput(e.target.value)} placeholder="Ask about Khan Productions"/><button className="action" disabled={busy||!input.trim()}>Send</button>{messages.length>0&&<button type="button" disabled={busy} className="text-sm underline" onClick={()=>{setMessages([]);setError('');}}>Clear conversation</button>}</form></section>}</>}
