import { useEffect, useState } from 'react';
import { BookOpen } from 'lucide-react';
import { useCatalogue, categoryNames, catalogueAsset } from '@/contexts/CatalogueContext';
import { useCataloguePages, CatalogueControls, CataloguePagination } from './CatalogueControls';
export default function Books(){
 const catalogue=useCatalogue();const {books}=catalogue;const [query,setQuery]=useState(''),[genre,setGenre]=useState('All Books');const categories=['All Books',...categoryNames(catalogue,'books')];useEffect(()=>{if(!categories.includes(genre))setGenre('All Books');},[catalogue,genre]);const filtered=books.filter(b=>(genre==='All Books'||b.genre===genre)&&`${b.title} ${b.author}`.toLowerCase().includes(query.trim().toLowerCase()));const paging=useCataloguePages(filtered,query+'|'+genre);
 function reset(){setQuery('');setGenre('All Books');}
 return <section id="books" className="section-shell"><div className="section-inner"><p className="eyebrow">Read & learn</p><h2 className="section-heading">Books Library</h2><p className="section-description">Search by title or author and choose a genre. For Google Drive books, use its Download button to save the PDF.</p><div className="tool-panel mt-8"><div className="grid gap-4 sm:grid-cols-2"><label htmlFor="book-search">Search books<input id="book-search" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Book title or author"/></label><label htmlFor="book-genre">Genre<select aria-label="Genre" id="book-genre" value={genre} onChange={e=>setGenre(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label></div><CatalogueControls paging={paging} id="books"/><div className="flex flex-wrap items-center gap-3"><p role="status" className="text-sm text-muted-foreground">{filtered.length} books · {genre}</p>{(query||genre!=='All Books')&&<button className="secondary-action" onClick={reset}>Clear filters</button>}</div></div><div className={`catalogue-grid book-grid mt-6 ${paging.compact?'compact':''}`}>{paging.items.map(b=><article className="catalogue-card" key={b.id}><div className="catalogue-image book-image">{b.cover?<img src={catalogueAsset(b.cover)} alt={`${b.title} book cover`} loading="lazy" decoding="async"/>:<div className="book-placeholder"><BookOpen aria-hidden="true"/><p>{b.title}</p><span>{b.author}</span></div>}</div><div className="catalogue-body"><p className="text-xs text-muted-foreground">{b.genre}</p><h3 className="font-semibold leading-snug">{b.title}</h3><p className="text-sm text-muted-foreground">{b.author}</p><div className="catalogue-details mt-auto"><a className="action w-full" href={catalogueAsset(b.file)} target="_blank" rel="noopener noreferrer" aria-label={`Read ${b.title} (opens in a new tab)`}>Read / download PDF</a></div></div></article>)}</div>{!filtered.length&&<div className="tool-panel mt-6"><p>No matching books. Try another title or genre.</p><button className="secondary-action" onClick={reset}>Show all books</button></div>}<CataloguePagination paging={paging}/></div></section>;
}
