import {useState, type FormEvent} from 'react';
import {categoryNames, type Catalogue, type CatalogueKind, type Category} from '@/contexts/CatalogueContext';

type Props={kind:CatalogueKind;catalogue:Catalogue;busy:boolean;request:<T>(path:string,method:string,body:unknown)=>Promise<T>;onChanged:()=>Promise<void>;onError:(message:string)=>void;setBusy:(value:boolean)=>void};
export default function CategoryManager({kind,catalogue,busy,request,onChanged,onError,setBusy}:Props){
 const [name,setName]=useState(''),[visible,setVisible]=useState(true),[original,setOriginal]=useState<string|null>(null),[notice,setNotice]=useState('');
 const categories=catalogue.categories?.[kind]||categoryNames(catalogue,kind,true).map(name=>({name,visible:true}));
 function reset(){setName('');setVisible(true);setOriginal(null);}
 async function save(event:FormEvent){event.preventDefault();setBusy(true);onError('');setNotice('');try{await request('/categories/'+kind,original===null?'POST':'PUT',{name,visible,...(original===null?{}:{oldName:original})});await onChanged();reset();setNotice('Category saved.');}catch(e){onError((e as Error).message);}finally{setBusy(false);}}
 async function remove(category:Category){if(!window.confirm(`Delete category “${category.name}”?`))return;setBusy(true);onError('');try{await request('/categories/'+kind,'DELETE',{name:category.name});await onChanged();if(original===category.name)reset();setNotice('Category deleted.');}catch(e){onError((e as Error).message);}finally{setBusy(false);}}
 return <section className="tool-panel mt-6" aria-labelledby="category-manager-heading"><h2 id="category-manager-heading" className="text-xl font-semibold">Manage {kind==='products'?'product categories':kind==='books'?'book genres':'music genres'}</h2><p className="text-sm text-muted-foreground">Renaming a category updates its items. Hiding removes it from visitor filters; its published items remain in the all-items view.</p><form onSubmit={save} className="grid gap-3 sm:grid-cols-2"><label htmlFor="category-name">Category name<input id="category-name" required maxLength={100} value={name} disabled={busy} onChange={e=>setName(e.target.value)} placeholder="For example: Accessories"/></label><label htmlFor="category-visible" className="flex items-center gap-2"><input id="category-visible" type="checkbox" checked={visible} disabled={busy} onChange={e=>setVisible(e.target.checked)}/>Show in visitor filters</label><div className="flex flex-wrap gap-2 sm:col-span-2"><button className="action" disabled={busy}>{original===null?'Add category':'Save category'}</button>{original!==null&&<button type="button" className="secondary-action" disabled={busy} onClick={reset}>Cancel category edit</button>}</div></form><ul className="space-y-2">{categories.map(category=><li className="admin-item" key={category.name}><div className="min-w-0 break-words"><strong>{category.name}</strong><p className="text-sm text-muted-foreground">{category.visible?'Visible in filters':'Hidden from filters'}</p></div><div className="flex shrink-0 gap-2"><button className="secondary-action" disabled={busy} onClick={()=>{setOriginal(category.name);setName(category.name);setVisible(category.visible);setNotice('');}}>Edit<span className="sr-only"> category {category.name}</span></button><button className="secondary-action text-destructive" disabled={busy} onClick={()=>void remove(category)}>Delete<span className="sr-only"> category {category.name}</span></button></div></li>)}</ul>{!categories.length&&<p>No categories yet. Add your first category above.</p>}{notice&&<p role="status">{notice}</p>}</section>;
}
