import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { apiBase } from '@/contexts/CatalogueContext';
const support='khanproductions7867@gmail.com';
export default function Contact(){
 const [enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState('');
 useEffect(()=>{const controller=new AbortController();fetch(apiBase+'/api/contact/config',{signal:controller.signal}).then(r=>r.ok?r.json():null).then(data=>setEnabled(data?.enabled===true)).catch(()=>{});return()=>controller.abort();},[]);
 return <section id="contact" className="section-shell bg-muted/30"><div className="section-inner"><p className="eyebrow">Get in touch</p><h2 className="section-heading">Contact & support</h2><p className="section-description">{enabled?'Send a question or tell us about a website problem.':'Ask a question or tell us about a problem. Prepare an email to send from your mail application.'}</p><div className="mt-8 grid gap-6 md:grid-cols-2"><form className="tool-panel" onSubmit={async e=>{
  e.preventDefault();if(busy)return;const form=e.currentTarget,data=new FormData(form);const body=Object.fromEntries(data.entries());
  if(!enabled){window.location.href=`mailto:${support}?subject=${encodeURIComponent(String(body.subject))}&body=${encodeURIComponent(`Name: ${body.name}\nReply email: ${body.email}\n\n${body.message}`)}`;setStatus('Email draft requested. Review and send it in your mail application.');return;}
  setBusy(true);setStatus('Submitting your message…');
  try{const response=await fetch(apiBase+'/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(20000)});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'Your message could not be submitted. Please use the email link.');setStatus('Your message was accepted for email delivery. Thank you for contacting us.');form.reset();}catch(error){setStatus(error instanceof Error?error.message:'Sending failed. Please use the support email link.');}finally{setBusy(false);}
 }}><label htmlFor="contact-name">Name</label><input id="contact-name" name="name" autoComplete="name" required maxLength={100}/><label htmlFor="contact-email">Email</label><input id="contact-email" type="email" name="email" autoComplete="email" required maxLength={200}/><label htmlFor="contact-subject">Subject</label><input id="contact-subject" name="subject" required maxLength={200}/><label htmlFor="contact-message">Message</label><textarea id="contact-message" name="message" rows={4} required maxLength={3000}/><div hidden aria-hidden="true"><label htmlFor="contact-website">Leave empty</label><input id="contact-website" name="website" tabIndex={-1} autoComplete="off"/></div><p className="text-xs leading-relaxed text-muted-foreground">{enabled?'Your details and message are sent to our support inbox using Resend.':'Your email application handles sending this message.'} Please avoid sensitive information. <Link to="/privacy" className="underline">Privacy notice</Link></p><button className="action" disabled={busy}>{busy?'Submitting…':enabled?'Send message':'Prepare Email'}</button><p role="status" className="text-sm text-muted-foreground">{status}</p></form><div className="tool-panel self-start"><h3 className="text-lg font-semibold">Email support</h3><a className="block break-all text-primary underline" href={`mailto:${support}`}>{support}</a><h3 className="pt-4 font-semibold">Social</h3><a className="secondary-action" href="https://www.facebook.com/share/1FhSvbqPsA/" target="_blank" rel="noopener noreferrer">Facebook (new tab)</a><p className="text-sm text-muted-foreground">For help using the website, you can also open the AI assistant.</p></div></div></div></section>;
}
