import { useEffect, useState } from 'react';
import { ExternalLink, Star } from 'lucide-react';
import { useCatalogue, categoryNames, catalogueAsset } from '@/contexts/CatalogueContext';
import { useCataloguePages, CatalogueControls, CataloguePagination } from './CatalogueControls';
export default function FeaturedProducts(){
 const catalogue=useCatalogue();const {products}=catalogue;const [query,setQuery]=useState(''),[category,setCategory]=useState('All Products');
 const categories=['All Products',...categoryNames(catalogue,'products')];
 useEffect(()=>{if(!categories.includes(category))setCategory('All Products');},[catalogue,category]);const filtered=products.filter(p=>(category==='All Products'||p.category===category)&&`${p.title} ${p.description} ${p.category}`.toLowerCase().includes(query.trim().toLowerCase()));
 const paging=useCataloguePages(filtered,query+'|'+category);
 function reset(){setQuery('');setCategory('All Products');}
 return <section id="featured-products" aria-labelledby="shop-heading" className="section-shell bg-muted/30"><div className="section-inner"><p className="eyebrow">Curated marketplace</p><h2 id="shop-heading" className="section-heading">Shop products</h2><p className="section-description">Discover products by category. Purchases happen on Amazon; check current prices and availability there.</p><div className="tool-panel mt-8"><div className="grid gap-4 sm:grid-cols-2"><label htmlFor="product-search">Search products<input id="product-search" type="search" placeholder="Product name or category" value={query} onChange={e=>setQuery(e.target.value)}/></label><label htmlFor="product-category">Category<select aria-label="Category" id="product-category" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label></div><CatalogueControls paging={paging} id="products"/><div className="flex flex-wrap items-center gap-3"><p role="status" className="text-sm text-muted-foreground">{filtered.length} products · {category}</p>{(query||category!=='All Products')&&<button className="secondary-action" onClick={reset}>Clear filters</button>}</div></div><div className={`catalogue-grid mt-6 ${paging.compact?'compact':''}`}>{paging.items.map(p=><article key={p.id} className="catalogue-card"><div className="catalogue-image product-image"><img src={catalogueAsset(p.image)} alt={p.title} loading="lazy" decoding="async"/>{p.badge&&<span className="catalogue-badge">{p.badge}</span>}</div><div className="catalogue-body"><p className="text-xs text-muted-foreground">{p.category}</p><h3 className="text-lg font-semibold leading-snug">{p.title}</h3><details className="catalogue-details"><summary>Product details</summary><p>{p.description}</p></details><div className="mt-auto"><p className="my-3 flex items-center gap-2 text-sm text-muted-foreground"><Star size={16} aria-hidden="true"/>Listed rating: {p.rating}/5</p><a href={catalogueAsset(p.link)} className="action w-full" target="_blank" rel="noopener noreferrer" aria-label={`View ${p.title} on ${p.source||'Amazon'} (opens in a new tab)`}>View on {p.source||'Amazon'}<ExternalLink size={16} aria-hidden="true"/></a></div></div></article>)}</div>{!filtered.length&&<div className="tool-panel mt-6"><p>No products match your search.</p><button className="secondary-action" onClick={reset}>Show all products</button></div>}<CataloguePagination paging={paging}/></div></section>;
}
