import { useEffect,useState } from 'react';
import { Link,useLocation,useNavigate } from 'react-router-dom';
import { Sun,Moon,Menu,X,Search } from 'lucide-react';
import { useTheme } from '@/contexts/ThemeContext';
import { publicAsset } from '@/lib/public-asset';
const items=[['Home','home'],['Shop','featured-products'],['Tools','/tools'],['Library','/library'],['Music','/music-library'],['About','about'],['Contact','contact']];
export default function Navbar(){const {theme,setTheme}=useTheme();const navigate=useNavigate();const [search,setSearch]=useState('');const [open,setOpen]=useState(false);const location=useLocation();const [active,setActive]=useState('');
useEffect(()=>{setSearch(new URLSearchParams(location.search).get('q')||'');},[location.search]);
useEffect(()=>{setOpen(false);if(location.pathname!=='/'){setActive(location.pathname==='/library'?'/library':location.pathname==='/music-library'?'/music-library':'/tools');return;}const sections=items.map(([,id])=>document.getElementById(id)).filter(Boolean);const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)setActive(e.target.id);},{rootMargin:'-15% 0px -65% 0px'});sections.forEach(s=>observer.observe(s!));return()=>observer.disconnect();},[location]);
return <><a href="#main-content" className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded focus:bg-background focus:p-3">Skip to content</a><header className="fixed inset-x-0 top-0 z-40 border-b border-border bg-background/95 backdrop-blur"><nav aria-label="Main navigation" className="mx-auto max-w-7xl px-4 sm:px-6"><div className="nav-main flex min-h-20 items-center justify-between gap-3"><Link to="/#home" className="shrink-0" aria-label="Khan Productions home"><img src={publicAsset('brand-logo.png')} alt="Khan Productions" className="h-auto w-40 sm:w-48 dark:brightness-0 dark:invert"/></Link>{location.pathname==='/'&&<form role="search" className="header-search" onSubmit={e=>{e.preventDefault();navigate({pathname:'/',search:search.trim()?'?'+new URLSearchParams({q:search.trim()}).toString():'',hash:'#featured-products'});document.getElementById('featured-products')?.scrollIntoView({behavior:'smooth'});}}><label className="sr-only" htmlFor="header-product-search">Search shop products</label><input id="header-product-search" type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products…"/><button type="submit" aria-label="Submit product search"><Search size={20}/></button></form>}<div className="hidden items-center gap-1 xl:flex">{items.map(([name,id])=><Link key={id} to={id.startsWith('/')?id:`/#${id}`} aria-current={active===id?'location':undefined} className={`rounded-lg px-3 py-3 text-sm font-medium ${active===id?'bg-muted text-primary':'text-muted-foreground hover:text-foreground'}`}>{name}</Link>)}</div><div className="flex items-center gap-2"><button aria-label={`Switch to ${theme==='dark'?'light':'dark'} mode`} onClick={()=>setTheme(theme==='dark'?'light':'dark')} className="flex h-11 w-11 items-center justify-center rounded-lg hover:bg-muted">{theme==='dark'?<Sun aria-hidden="true" size={20}/>:<Moon aria-hidden="true" size={20}/>}</button><button className="flex h-11 w-11 items-center justify-center xl:hidden" aria-expanded={open} aria-controls="mobile-nav" aria-label={open?'Close navigation':'Open navigation'} onClick={()=>setOpen(!open)}>{open?<X aria-hidden="true"/>:<Menu aria-hidden="true"/>}</button></div></div>{open&&<div id="mobile-nav" className="grid grid-cols-2 gap-1 border-t border-border py-3 xl:hidden">{items.map(([name,id])=><Link onClick={()=>setOpen(false)} key={id} to={id.startsWith('/')?id:`/#${id}`} className="rounded-lg px-3 py-3 hover:bg-muted" aria-current={active===id?'location':undefined}>{name}</Link>)}</div>}</nav></header></>}
